# Generated by Django 4.2.8 on 2025-05-15 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_add_default_genders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
